spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

springdoc:
  swagger-ui:
    path: /swagger.html

sentry:
  dsn: https://82cfa8b18e929161d2d251a19148b95c@o4506590919655424.ingest.sentry.io/4506591131402240
  traces-sample-rate: 1.0